get file description instead of process name
sindresorhus/active-win pull request #131
Opened 2022-01-13 18:30 UTC by pityulin

https://github.com/sindresorhus/active-win/issues/130#issue-1099226677

2022-01-17 18:23 UTC, sindresorhus commented
Linting is failing.

2022-01-17 18:23 UTC, sindresorhus commented
have you thoroughly tested your changes? You're changing a lot of stuff and I don't have Windows to test at the moment.

2022-01-17 18:27 UTC, sindresorhus requested changes

2022-01-17 18:27 UTC, sindresorhus commented on lib/windows.js
> +	return 0x040904E4;
This should be a constant with a descriptive name.

2022-01-17 18:27 UTC, sindresorhus commented
I'd like to see some more code comments.

2022-01-19 06:21 UTC, sindresorhus commented on lib/windows.js
> +function getLangId(mem) {
```suggestion
function getLanguageId(mem) {
```

2022-01-19 06:21 UTC, sindresorhus commented on lib/windows.js
> +	return ref.allocCString(string + '\0', 'ucs2');
```suggestion
	return ref.allocCString(`${string}\0`, 'ucs2');
```

2022-01-19 06:21 UTC, sindresorhus commented on lib/windows.js
> +function wstring(string) {
```suggestion
function toWstring(string) {
```

2022-01-19 06:21 UTC, sindresorhus commented on lib/windows.js
> +function getFileVersionString(mem, name) {
> mem

Don't use abbreviations

2022-01-19 06:22 UTC, sindresorhus commented on lib/windows.js
> +		const buf = ref.readPointer(value, 0, size.deref() * wchar.size);
```suggestion
		const buffer = ref.readPointer(value, 0, size.deref() * wchar.size);
```

2022-01-19 06:22 UTC, sindresorhus commented on .vscode/launch.json
> +}
This should not be committed.

2022-01-21 10:27 UTC, sindresorhus commented
> have you thoroughly tested your changes?

I never got a reply to this.

2022-01-21 10:28 UTC, sindresorhus commented
Linting is failing.

2022-01-24 15:12 UTC, supercoww commented on lib/windows.js
> +			processName = fileDescription.trim() || processName;
`fileDescription` can be undefined for some apps. For me it crashed when opening Windows Terminal or Snipping tool.

```
D:\projects\active-win\node_modules\.pnpm\ffi-napi@4.0.3\node_modules\ffi-napi\lib\_foreign_function.js:61      
    bindings.ffi_call(cif, funcPtr, result, argsList);
             ^

Error: TypeError: Cannot read properties of undefined (reading 'trim')
    at Object.proxy [as EnumChildWindows] (D:\projects\active-win\node_modules\.pnpm\ffi-napi@4.0.3\node_modules\ffi-napi\lib\_foreign_function.js:61:14)    at getSubWindowRealProcessNameAndPath (D:\projects\active-win\lib\windows.js:143:9)
    at Function.windows [as sync] (D:\projects\active-win\lib\windows.js:236:32)
    at Function.module.exports.sync (D:\projects\active-win\index.js:29:38)
```

2022-01-27 13:33 UTC, merged