Add disableScreenRecordingPermission option
sindresorhus/active-win pull request #96
Opened 2021-01-28 01:00 UTC by wrgoto

### Why

One of the significant drawbacks is the library asking for Screen Recording permissions for macOS versions 10.15 and newer. Even though the library doesn't actually record the screen, it is required to get the title of the active window. For those who do not need the window title, there should be an option to forgo the Screen Recording permission check.

### Changes

- Add a `disableScreenRecordingPermission` option.
- Skip the screen recording permission check if true.
- Return an empty string as the title if true.

### Related

- https://github.com/sindresorhus/active-win/issues/88
- https://github.com/sindresorhus/active-win/pull/67

2021-01-28 16:52 UTC, sindresorhus commented
See the feedback in https://github.com/sindresorhus/active-win/pull/67/files. There should be an option for each check.

2021-01-28 16:53 UTC, sindresorhus commented on index.d.ts
> +		disableScreenRecordingPermission: boolean;
```suggestion
		screenRecordingPermission: boolean;
```

2021-01-28 16:53 UTC, sindresorhus commented on index.d.ts
> +		Setting this to true will prevent the Screen Recording permission prompt on macOS versions 10.15 and newer. The `title` property will always be set to an empty string.
Should mention the default value with `@default`.

https://github.com/sindresorhus/typescript-definition-style-guide

2021-01-28 16:54 UTC, sindresorhus commented on readme.md
> +- `disableScreenRecordingPermission` *(boolean)* - Disable the screen recording permission check (macOS). Setting this to true will prevent the Screen Recording permission prompt on macOS versions 10
Should use formatting like https://github.com/sindresorhus/boxen#options

2021-01-28 16:54 UTC, sindresorhus commented on readme.md
> +### activeWin(options)
```suggestion
### activeWin(options?)
```

2021-01-28 18:36 UTC, achuinard commented
@wrgoto Thanks for your contributions!

2021-01-28 18:38 UTC, wrgoto commented
@sindresorhus I agree there should be an option for each check, but I haven't verified the extent of removing the accessibility check. I'm not entirely sure if it is limited to the `url` property. I can investigate in a separate issue and PR.

2021-01-29 17:25 UTC, achuinard commented
@sindresorhus are you looking to get this merged soon?

2021-03-07 11:55 UTC, sindresorhus requested changes

2021-03-07 11:55 UTC, sindresorhus commented on index.test-d.ts
> +const result = activeWin.sync({ screenRecordingPermission: false });
```suggestion
const result = activeWin.sync({screenRecordingPermission: false});
```

2021-03-07 11:55 UTC, sindresorhus commented on lib/macos.js
> +		args.push('--disable-screen-recording-permission');
```suggestion
		args.push('--no-screen-recording-permission');
```

`--no` is the convention for inverted flags.

2021-03-07 11:55 UTC, sindresorhus commented on readme.md
> +Enable the screen recording permission check (macOS). Setting this to `false` will prevent the Screen Recording permission prompt on macOS versions 10.15 and newer. The `title` property in the result
```suggestion
Enable the screen recording permission check. Setting this to `false` will prevent the screen recording permission prompt on macOS versions 10.15 and newer. The `title` property in the result will always be set to an empty string.
```

2021-03-07 11:55 UTC, sindresorhus commented on readme.md
> +Returns a `Promise<Object>` with the result, or `Promise<undefined>` if there is no active window or if the information is not available.
```suggestion
Returns a `Promise<object>` with the result, or `Promise<undefined>` if there is no active window or if the information is not available.
```

2021-03-07 11:55 UTC, sindresorhus commented on readme.md
> +##### screenRecordingPermission
```suggestion
##### screenRecordingPermission **(macOS only)**
```

2021-03-07 11:55 UTC, sindresorhus commented on readme.md
> +#### options
You don't need to document the `options` twice.

2021-03-07 11:55 UTC, sindresorhus commented on index.d.ts
> +		Enable the screen recording permission check (macOS).
```suggestion
		Enable the screen recording permission check. _(macOS)_
```

2021-03-07 11:55 UTC, sindresorhus commented on index.d.ts
> +		Setting this to `false` will prevent the Screen Recording permission prompt on macOS versions 10.15 and newer. The `title` property in the result will always be set to an empty string.
```suggestion
		Setting this to `false` will prevent the screen recording permission prompt on macOS versions 10.15 and newer. The `title` property in the result will always be set to an empty string.
```

2021-03-07 11:55 UTC, sindresorhus commented on index.d.ts
> +		screenRecordingPermission: boolean;
```suggestion
		readonly screenRecordingPermission: boolean;
```

2021-03-07 11:55 UTC, sindresorhus commented
The PR title needs to be updated.

2021-04-07 09:15 UTC, merged